site_name: Siddhi-IO-WSO2Event
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi IO WSO2Event: index.md
- About:
  - License: about/license.md
- Api:
  - 4.0.1-SNAPSHOT: api/4.0.1-SNAPSHOT.md
- API Docs:
  - 4.0.8: api/4.0.8.md
  - 4.0.7: api/4.0.7.md
  - 4.0.6: api/4.0.6.md
  - 4.0.5: api/4.0.5.md
  - 4.0.4: api/4.0.4.md
  - 4.0.3: api/4.0.3.md
  - 4.0.2: api/4.0.2.md
  - latest: api/latest.md
theme: material
